AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  BentoConfig:
    Type: String
    Description: >
      A YAML configuration for the Bento pipeline, can include any traditional
      sections except for input or buffer.
    Default: |
      pipeline:
        processors:
        - type: metadata
          metadata:
            operator: set
            key: AWS_LAMBDA_FUNCTION_VERSION
            value: "${AWS_LAMBDA_FUNCTION_VERSION}"

Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: not.used.for.provided.al2.runtime
      Runtime: provided.al2
      Architectures: [ arm64 ]
      CodeUri: 'target/serverless/bento-lambda-al2.zip'
      Environment:
        Variables:
          BENTO_CONFIG:
            Ref: BentoConfig
