builds:
  - id: bento
    main: cmd/bento/main.go
    binary: bento
    goos: [ darwin ]
    goarch: [ arm64 ]
    goarm: [ 6, 7 ]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X main.Version={{.Version}}
      -X main.DateBuilt={{.Date}}
dist: target/dist
release:
  github:
    owner: jem-davies
    name: bento
  prerelease: auto
  disable: false
