# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BentoPython.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'BentoPython.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42\x65ntoPython.proto\x12\nbento.grpc\"\x18\n\x08\x42\x65ntoMsg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x19\n\tPythonRsp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32G\n\x0b\x42\x65ntoPython\x12\x38\n\x07Process\x12\x14.bento.grpc.BentoMsg\x1a\x15.bento.grpc.PythonRsp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BentoPython_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BENTOMSG']._serialized_start=33
  _globals['_BENTOMSG']._serialized_end=57
  _globals['_PYTHONRSP']._serialized_start=59
  _globals['_PYTHONRSP']._serialized_end=84
  _globals['_BENTOPYTHON']._serialized_start=86
  _globals['_BENTOPYTHON']._serialized_end=157
# @@protoc_insertion_point(module_scope)
